// year, make, model, body_styles
const allCars = [
    { year: 2018, make: 'Acura', model: 'ILX', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Acura', model: 'MDX', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Acura', model: 'NSX', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Acura', model: 'RDX', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Acura', model: 'RLX', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Acura', model: 'RLX Sport Hybrid', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Acura', model: 'TLX', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Acura', model: 'MDX Sport Hybrid', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Alfa Romeo', model: '4C Spider', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'Alfa Romeo', model: 'Giulia', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Alfa Romeo', model: 'Stelvio', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Alfa Romeo', model: '4C', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Aston Martin',  model: 'Vanquish S', bodyStyles: ['Convertible', 'Coupe'] },
    { year: 2018, make: 'Aston Martin',  model: 'DB11', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Audi', model: 'A3', bodyStyles: ['Convertible', 'Sedan'] },
    { year: 2018, make: 'Audi', model: 'A3 Sportback e-tron', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Audi', model: 'A4', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'A4 allroad', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Audi', model: 'A5', bodyStyles: ['Convertible', 'Coupe', 'Sedan'] },
    { year: 2018, make: 'Audi', model: 'A6', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'A7', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'A8', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'Q3', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Audi', model: 'Q7', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Audi', model: 'R8', bodyStyles: ['Coupe', 'Convertible'] },
    { year: 2018, make: 'Audi', model: 'RS 3', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'RS 7', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'S3', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'S4', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'S5', bodyStyles: ['Coupe', 'Sedan', 'Convertible'] },
    { year: 2018, make: 'Audi', model: 'S6', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'S7', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'S8', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Audi', model: 'SQ5', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Audi', model: 'TT',  bodyStyles: ['Convertible', 'Coupe'] },
    { year: 2018, make: 'Audi', model: 'RS 5', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Bentley', model: 'Bentayga', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Bentley', model: 'Continental', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'Bentley', model: 'Mulsanne', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'BMW', model: '3 Series', bodyStyles: ['Sedan', 'Wagon'] },
    { year: 2018, make: 'BMW', model: '6 Series', bodyStyles: ['Sedan', 'Convertible'] },
    { year: 2018, make: 'BMW', model: '7 Series', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'BMW', model: 'i3', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'BMW', model: 'M3', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'BMW', model: 'M4', bodyStyles: ['Convertible', 'Coupe'] },
    { year: 2018, make: 'BMW', model: 'M5', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'BMW', model: 'M6', bodyStyles: ['Coupe', 'Convertible'] },
    { year: 2018, make: 'BMW', model: 'X1', bodyStyles: ['SUV'] },
    { year: 2018, make: 'BMW', model: 'X2', bodyStyles: ['SUV'] },
    { year: 2018, make: 'BMW', model: 'X3', bodyStyles: ['SUV'] },
    { year: 2018, make: 'BMW', model: 'X5', bodyStyles: ['SUV'] },
    { year: 2018, make: 'BMW', model: 'X5 M', bodyStyles: ['SUV'] },
    { year: 2018, make: 'BMW', model: 'X6', bodyStyles: ['SUV'] },
    { year: 2018, make: 'BMW', model: 'M2', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'BMW', model: 'X6 M', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Buick', model: 'Cascada', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'Buick', model: 'Enclave', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Buick', model: 'Encore', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Buick', model: 'Envision', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Buick', model: 'LaCrosse', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Buick', model: 'Regal Sportback', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Buick', model: 'Regal TourX', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Cadillac', model: 'ATS', bodyStyles: ['Sedan', 'Coupe'] },
    { year: 2018, make: 'Cadillac', model: 'ATS-V', bodyStyles: ['Coupe', 'Sedan'] },
    { year: 2018, make: 'Cadillac', model: 'CT6', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Cadillac', model: 'CTS', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Cadillac', model: 'CTS-V', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Cadillac', model: 'Escalade', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Cadillac', model: 'Escalade ESV', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Cadillac', model: 'XTS', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Chevrolet', model: 'Bolt EV', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Chevrolet', model: 'City Express', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Chevrolet', model: 'Colorado Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chevrolet', model: 'Colorado Extended Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chevrolet', model: 'Corvette', bodyStyles: ['Coupe', 'Convertible'] },
    { year: 2018, make: 'Chevrolet', model: 'Silverado 1500 Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chevrolet', model: 'Silverado 1500 Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chevrolet', model: 'Silverado 2500 HD Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chevrolet', model: 'Silverado 3500 HD Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chevrolet', model: 'Sonic', bodyStyles: ['Sedan', 'Hatchback'] },
    { year: 2018, make: 'Chevrolet', model: 'Spark', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Chevrolet', model: 'Suburban', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Chevrolet', model: 'Tahoe', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Chevrolet', model: 'Traverse', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Chevrolet', model: 'Trax', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Chevrolet', model: 'Express 2500 Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Chevrolet', model: 'Express 2500 Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Chevrolet', model: 'Express 3500 Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Chevrolet', model: 'Express 3500 Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Chevrolet', model: 'Silverado 2500 HD Double Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chevrolet', model: 'Silverado 2500 HD Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chevrolet', model: 'Silverado 3500 HD Double Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chevrolet', model: 'Silverado 3500 HD Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Chrysler', model: '300', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Chrysler', model: 'Pacifica', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Chrysler', model: 'Pacifica Hybrid', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Dodge', model: 'Durango', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Dodge', model: 'Grand Caravan Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Dodge', model: 'Journey', bodyStyles: ['SUV'] },
    { year: 2018, make: 'FIAT', model: '124 Spider', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'FIAT', model: '500L', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'FIAT', model: '500X', bodyStyles: ['SUV'] },
    { year: 2018, make: 'FIAT', model: '500', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'FIAT', model: '500 Abarth', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'FIAT', model: '500c', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'FIAT', model: '500c Abarth', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'FIAT', model: '500e', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Ford', model: 'C-MAX Hybrid', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Ford', model: 'EcoSport', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Ford', model: 'Edge', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Ford', model: 'Expedition', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Ford', model: 'Expedition MAX', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Ford', model: 'Explorer', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Ford', model: 'F150 Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ford', model: 'F150 Super Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ford', model: 'F250 Super Duty Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ford', model: 'F250 Super Duty Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ford', model: 'F250 Super Duty Super Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ford', model: 'Fiesta', bodyStyles: ['Sedan', 'Hatchback'] },
    { year: 2018, make: 'Ford', model: 'Flex', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Ford', model: 'Focus', bodyStyles: ['Sedan', 'Hatchback'] },
    { year: 2018, make: 'Ford', model: 'Fusion Energi', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Ford', model: 'Mustang', bodyStyles: ['Coupe', 'Convertible'] },
    { year: 2018, make: 'Ford', model: 'Taurus', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Ford', model: 'Transit 250 Van', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Ford', model: 'Transit Connect Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Ford', model: 'F350 Super Duty Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ford', model: 'F350 Super Duty Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ford', model: 'F350 Super Duty Super Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ford', model: 'F450 Super Duty Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ford', model: 'Transit 150 Van', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Ford', model: 'Transit 150 Wagon', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Ford', model: 'Transit 350 HD Van', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Ford', model: 'Transit 350 Van', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Ford', model: 'Transit 350 Wagon', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Ford', model: 'Transit Connect Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Freightliner', model: 'Sprinter 2500 Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Freightliner', model: 'Sprinter 2500 Crew', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Freightliner', model: 'Sprinter 2500 Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Freightliner', model: 'Sprinter 3500 Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Freightliner', model: 'Sprinter 3500XD Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Genesis', model: 'G80', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Genesis', model: 'G90', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'GMC', model: 'Acadia', bodyStyles: ['SUV'] },
    { year: 2018, make: 'GMC', model: 'Canyon Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Canyon Extended Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Sierra 1500 Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Sierra 1500 Double Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Sierra 1500 Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Sierra 2500 HD Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Sierra 2500 HD Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Yukon', bodyStyles: ['SUV'] },
    { year: 2018, make: 'GMC', model: 'Yukon XL', bodyStyles: ['SUV'] },
    { year: 2018, make: 'GMC', model: 'Savana 2500 Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'GMC', model: 'Savana 2500 Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'GMC', model: 'Savana 3500 Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'GMC', model: 'Savana 3500 Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'GMC', model: 'Sierra 2500 HD Double Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Sierra 3500 HD Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Sierra 3500 HD Double Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'GMC', model: 'Sierra 3500 HD Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Honda', model: 'Accord', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Honda', model: 'Civic', bodyStyles: ['Coupe', 'Sedan', 'Hatchback'] },
    { year: 2018, make: 'Honda', model: 'Civic Type R', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Honda', model: 'Clarity Plug-in Hybrid', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Honda', model: 'CR-V', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Honda', model: 'Fit', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Honda', model: 'HR-V', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Honda', model: 'Odyssey', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Honda', model: 'Pilot', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Honda', model: 'Ridgeline', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Honda', model: 'Accord Hybrid', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Honda', model: 'Clarity Electric', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Honda', model: 'Clarity Fuel Cell', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Hyundai', model: 'Accent', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Hyundai', model: 'Elantra GT', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Hyundai', model: 'Ioniq Hybrid', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Hyundai', model: 'Ioniq Plug-in Hybrid', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Hyundai', model: 'Kona', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Hyundai', model: 'Santa Fe', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Hyundai', model: 'Santa Fe Sport', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Hyundai', model: 'Sonata', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Hyundai', model: 'Ioniq Electric', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Hyundai', model: 'Sonata Hybrid', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Hyundai', model: 'Sonata Plug-in Hybrid', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'INFINITI', model: 'Q50', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'INFINITI', model: 'Q60', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'INFINITI', model: 'Q70', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'INFINITI', model: 'QX60', bodyStyles: ['SUV'] },
    { year: 2018, make: 'INFINITI', model: 'QX80', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Jaguar', model: 'E-PACE', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Jaguar', model: 'F-TYPE', bodyStyles: ['Convertible', 'Coupe'] },
    { year: 2018, make: 'Jaguar', model: 'XE', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Jaguar', model: 'XF', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Jaguar', model: 'XJ', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Jeep', model: 'Cherokee', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Jeep', model: 'Compass', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Jeep', model: 'Grand Cherokee', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Jeep', model: 'Renegade', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Jeep', model: 'Wrangler', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Jeep', model: 'Wrangler Unlimited', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Kia', model: 'Cadenza', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Kia', model: 'Forte', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Kia', model: 'Forte5', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Kia', model: 'Niro', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Kia', model: 'Optima Hybrid', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Kia', model: 'Optima Plug-in Hybrid', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Kia', model: 'Rio', bodyStyles: ['Hatchback', 'Sedan'] },
    { year: 2018, make: 'Kia', model: 'Sedona', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Kia', model: 'Sorento', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Kia', model: 'Soul', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Kia', model: 'Soul EV', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Kia', model: 'Stinger', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Kia', model: 'Niro Plug-in Hybrid', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Lamborghini', model: 'Huracan', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Land Rover', model: 'Discovery', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Land Rover', model: 'Discovery Sport', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Land Rover', model: 'Range Rover', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Land Rover', model: 'Range Rover Evoque', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Land Rover', model: 'Range Rover Sport', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Land Rover', model: 'Range Rover Velar', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Lexus', model: 'ES', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Lexus', model: 'GS', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Lexus', model: 'GX', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Lexus', model: 'IS', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Lexus', model: 'LC', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Lexus', model: 'LS', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Lexus', model: 'LX', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Lexus', model: 'NX', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Lexus', model: 'RC', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Lexus', model: 'RX', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Lincoln', model: 'Continental', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Lincoln', model: 'MKC', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Lincoln', model: 'MKT', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Lincoln', model: 'MKX', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Lincoln', model: 'MKZ', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Lincoln', model: 'Navigator', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Lincoln', model: 'Navigator L', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Maserati', model: 'Ghibli', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Maserati', model: 'Levante', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Maserati', model: 'Quattroporte', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Mazda', model: 'CX-3', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mazda', model: 'CX-5', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mazda', model: 'CX-9', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mazda', model: 'MAZDA3', bodyStyles: ['Sedan', 'Hatchback'] },
    { year: 2018, make: 'Mazda', model: 'MAZDA6', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'C-Class', bodyStyles: ['Coupe', 'Sedan', 'Convertible'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'E-Class', bodyStyles: ['Convertible', 'Coupe', 'Sedan', 'Wagon'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'G-Class', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'GLA', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'GLC', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'GLE', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'GLS', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG C-Class', bodyStyles: ['Sedan', 'Coupe', 'Convertible'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG CLA', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG E-Class', bodyStyles: ['Sedan', 'Wagon'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG G-Class', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG GLA', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'S-Class', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'CLS', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'GLC Coupe', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG CLS', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG GLC Coupe', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG GLE', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG GLE Coupe', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG GT', bodyStyles: ['Coupe', 'Convertible'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG S-Class', bodyStyles: ['Convertible', 'Coupe', 'Sedan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG SL', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Mercedes-AMG SLC', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Metris Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Metris Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Metris WORKER Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Metris WORKER Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'SL', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'SLC', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Sprinter 2500 Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Sprinter 2500 Crew', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Sprinter 2500 Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Sprinter 3500 Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Mercedes- Benz', model: 'Sprinter 3500 XD Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'MINI', model: 'Clubman', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'MINI', model: 'Convertible', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'MINI', model: 'Hardtop 4 Door', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Mitsubishi', model: 'Eclipse Cross', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mitsubishi', model: 'Mirage', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Mitsubishi', model: 'Mirage G4', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Mitsubishi', model: 'Outlander', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mitsubishi', model: 'Outlander PHEV', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Mitsubishi', model: 'Outlander Sport', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Nissan', model: '370Z', bodyStyles: ['Convertible', 'Coupe'] },
    { year: 2018, make: 'Nissan', model: 'Armada', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Nissan', model: 'Frontier Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Nissan', model: 'Frontier King Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Nissan', model: 'GT-R', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Nissan', model: 'LEAF', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Nissan', model: 'Maxima', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Nissan', model: 'Murano', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Nissan', model: 'NV200', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Nissan', model: 'Pathfinder', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Nissan', model: 'Rogue Sport', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Nissan', model: 'Sentra', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Nissan', model: 'Titan Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Nissan', model: 'TITAN XD Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Nissan', model: 'Versa Note', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Nissan', model: 'Kicks', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Nissan', model: 'NV1500 Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Nissan', model: 'NV2500 HD Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Nissan', model: 'NV3500 HD Cargo', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Nissan', model: 'NV3500 HD Passenger', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Nissan', model: 'Titan King Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Nissan', model: 'TITAN Single Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Nissan', model: 'TITAN XD King Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Nissan', model: 'TITAN XD Single Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Porsche', model: '718 Boxster', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'Porsche', model: '718 Cayman', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Porsche', model: '911', bodyStyles: ['Coupe', 'Convertible'] },
    { year: 2018, make: 'Porsche', model: 'Cayenne', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Porsche', model: 'Macan', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Porsche', model: 'Panamera', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Ram', model: '1500 Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ram', model: '2500 Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ram', model: 'ProMaster City', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Ram', model: '2500 Mega Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ram', model: '2500 Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ram', model: '3500 Crew Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ram', model: '3500 Mega Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ram', model: '3500 Regular Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Ram', model: 'ProMaster Cargo Van,', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'smart', model: 'fortwo electric drive', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'smart', model: 'fortwo electric drive cabrio', bodyStyles: ['Convertible'] },
    { year: 2018, make: 'Subaru', model: 'BRZ', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Subaru', model: 'Crosstrek', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Subaru', model: 'Forester', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Subaru', model: 'Impreza', bodyStyles: ['Wagon', 'Sedan'] },
    { year: 2018, make: 'Subaru', model: 'Outback', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Subaru', model: 'WRX', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Tesla', model: 'Model 3', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Tesla', model: 'Model S', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Tesla', model: 'Model X', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Toyota', model: '4Runner', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Toyota', model: 'Avalon', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Toyota', model: 'Avalon Hybrid', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Toyota', model: 'Camry Hybrid', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Toyota', model: 'Corolla iM', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Toyota', model: 'Highlander', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Toyota', model: 'Highlander Hybrid', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Toyota', model: 'Land Cruiser', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Toyota', model: 'Prius', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Toyota', model: 'Prius c', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Toyota', model: 'Prius Prime', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Toyota', model: 'RAV4', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Toyota', model: 'RAV4 Hybrid', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Toyota', model: 'Sequoia', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Toyota', model: 'Sienna', bodyStyles: ['Van/Minivan'] },
    { year: 2018, make: 'Toyota', model: 'Tacoma Access Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Toyota', model: 'Tacoma Double Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Toyota', model: 'Tundra CrewMax', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Toyota', model: 'Tundra Double Cab', bodyStyles: ['Pickup'] },
    { year: 2018, make: 'Toyota', model: 'Yaris', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Toyota', model: 'Yaris iA', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Toyota', model: '86', bodyStyles: ['Coupe'] },
    { year: 2018, make: 'Toyota', model: 'Mirai', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Volkswagen', model: 'Atlas', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Volkswagen', model: 'Beetle', bodyStyles: ['Convertible', 'Hatchback'] },
    { year: 2018, make: 'Volkswagen', model: 'Golf', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Volkswagen', model: 'Golf Alltrack', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Volkswagen', model: 'Golf GTI', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Volkswagen', model: 'Golf R', bodyStyles: ['Hatchback'] },
    { year: 2018, make: 'Volkswagen', model: 'Golf SportWagen', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Volkswagen', model: 'Jetta', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Volkswagen', model: 'Passat', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Volkswagen', model: 'Tiguan', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Volkswagen', model: 'Tiguan Limited', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Volvo', model: 'S60', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Volvo', model: 'S90', bodyStyles: ['Sedan'] },
    { year: 2018, make: 'Volvo', model: 'V60', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Volvo', model: 'V90', bodyStyles: ['Wagon'] },
    { year: 2018, make: 'Volvo', model: 'XC60', bodyStyles: ['SUV'] },
    { year: 2018, make: 'Volvo', model: 'XC90', bodyStyles: ['SUV'] }
]

function sortCarsByMake(unsortedCars) {
    
    const carMakes = unsortedCars.reduce((retArray, car) => {
        if (!retArray.includes(car.make)) {
            return retArray.concat(car.make)
        // if (!retArray.includes({ make: car.make })) {
        //     return retArray.concat({ make: car.make })
        }
        // console.log()
        // if (!arr.includes(car.make)) {
        //     // return { [car.make]: { cars: [] } }
        //     return car.make
        // }
        return retArray;
    }, []).map((car) =>( {make: car} ))

    // let carModels = await carMakes.map((make, index, arr)=> {

    // })
    
    return carMakes;
}


function AddModels(carMakes, unsortedCars) {
    return carMakes.map((car) =>{
        return unsortedCars.reduce((retObj, currentCar)=>{
            if (retObj.make === currentCar.make) {
                retObj.models = retObj.models.concat({
                    model: currentCar.model,
                    year: currentCar.year,
                    bodyStyles: currentCar.bodyStyles
                })
            }
            return retObj;
        }, { make: car.make , models: []})
    })
}

let makesAndModels = AddModels(sortCarsByMake(allCars), allCars);

export default makesAndModels;